spring.thymeleaf.prefix: classpath:/templates/

#开发、生产环境配置
spring:
  #dev|test|pro
  profiles:
    active: pro
  #修改tomcatĬ最大文件上传大小
  servlet:
    multipart:
      enabled: true
      max-file-size: 100MB
      max-request-size: 100MB
  http:
    encoding:
      force: true
      charset: utf-8
      enabled: true
  redis:
    host: 1.117.62.42
    password: sahkbnk.?(da
    database: 10
    jedis:
      pool:
        max-active: 8
        max-idle: 8
        min-idle: 0
    port: 6379


##mybatis配置
#mybatis.mapperLocations: classpath:mapper/*.xml
#mybatis.typeAliasesPackage: com.rxkj.entity
##mybatis.configuration.cache-enabled: true
